//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummonerStats.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMatchHistory
    {
        [Key]
        public long matchIndex { get; set; }
        public int id { get; set; }
        public long timestamp { get; set; }
        public int champion { get; set; }
        public string region { get; set; }
        public string queue { get; set; }
        public string season { get; set; }
        public long matchId { get; set; }
        public string role { get; set; }
        public string platformId { get; set; }
        public string lane { get; set; }
    }
}
