namespace SummonerStats.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class InitialCreate : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.MatchDetailsModels",
                c => new
                    {
                        matchIndex = c.Int(nullable: false, identity: true),
                        region = c.String(),
                        matchType = c.String(),
                        matchCreation = c.Long(nullable: false),
                        platformId = c.String(),
                        matchMode = c.String(),
                        mapId = c.Int(nullable: false),
                        season = c.String(),
                        queueType = c.String(),
                        matchId = c.Long(nullable: false),
                        matchDuration = c.Int(nullable: false),
                        winner = c.String(),
                        p1Name = c.String(),
                        p2Name = c.String(),
                        p3Name = c.String(),
                        p4Name = c.String(),
                        p5Name = c.String(),
                        p6Name = c.String(),
                        p7Name = c.String(),
                        p8Name = c.String(),
                        p9Name = c.String(),
                        p10Name = c.String(),
                        p1Spell1 = c.Int(nullable: false),
                        p1Spell2 = c.Int(nullable: false),
                        p2Spell1 = c.Int(nullable: false),
                        p2Spell2 = c.Int(nullable: false),
                        p3Spell1 = c.Int(nullable: false),
                        p3Spell2 = c.Int(nullable: false),
                        p4Spell1 = c.Int(nullable: false),
                        p4Spell2 = c.Int(nullable: false),
                        p5Spell1 = c.Int(nullable: false),
                        p5Spell2 = c.Int(nullable: false),
                        p6Spell1 = c.Int(nullable: false),
                        p6Spell2 = c.Int(nullable: false),
                        p7Spell1 = c.Int(nullable: false),
                        p7Spell2 = c.Int(nullable: false),
                        p8Spell1 = c.Int(nullable: false),
                        p8Spell2 = c.Int(nullable: false),
                        p9Spell1 = c.Int(nullable: false),
                        p9Spell2 = c.Int(nullable: false),
                        p10Spell1 = c.Int(nullable: false),
                        p10Spell2 = c.Int(nullable: false),
                        p1Champ = c.Int(nullable: false),
                        p2Champ = c.Int(nullable: false),
                        p3Champ = c.Int(nullable: false),
                        p4Champ = c.Int(nullable: false),
                        p5Champ = c.Int(nullable: false),
                        p6Champ = c.Int(nullable: false),
                        p7Champ = c.Int(nullable: false),
                        p8Champ = c.Int(nullable: false),
                        p9Champ = c.Int(nullable: false),
                        p10Champ = c.Int(nullable: false),
                        p1Tier = c.String(),
                        p2Tier = c.String(),
                        p3Tier = c.String(),
                        p4Tier = c.String(),
                        p5Tier = c.String(),
                        p6Tier = c.String(),
                        p7Tier = c.String(),
                        p8Tier = c.String(),
                        p9Tier = c.String(),
                        p10Tier = c.String(),
                        p1Item1 = c.Int(nullable: false),
                        p1Item2 = c.Int(nullable: false),
                        p1Item3 = c.Int(nullable: false),
                        p1Item4 = c.Int(nullable: false),
                        p1Item5 = c.Int(nullable: false),
                        p1Item6 = c.Int(nullable: false),
                        p2Item1 = c.Int(nullable: false),
                        p2Item2 = c.Int(nullable: false),
                        p2Item3 = c.Int(nullable: false),
                        p2Item4 = c.Int(nullable: false),
                        p2Item5 = c.Int(nullable: false),
                        p2Item6 = c.Int(nullable: false),
                        p3Item1 = c.Int(nullable: false),
                        p3Item2 = c.Int(nullable: false),
                        p3Item3 = c.Int(nullable: false),
                        p3Item4 = c.Int(nullable: false),
                        p3Item5 = c.Int(nullable: false),
                        p3Item6 = c.Int(nullable: false),
                        p4Item1 = c.Int(nullable: false),
                        p4Item2 = c.Int(nullable: false),
                        p4Item3 = c.Int(nullable: false),
                        p4Item4 = c.Int(nullable: false),
                        p4Item5 = c.Int(nullable: false),
                        p4Item6 = c.Int(nullable: false),
                        p5Item1 = c.Int(nullable: false),
                        p5Item2 = c.Int(nullable: false),
                        p5Item3 = c.Int(nullable: false),
                        p5Item4 = c.Int(nullable: false),
                        p5Item5 = c.Int(nullable: false),
                        p5Item6 = c.Int(nullable: false),
                        p6Item1 = c.Int(nullable: false),
                        p6Item2 = c.Int(nullable: false),
                        p6Item3 = c.Int(nullable: false),
                        p6Item4 = c.Int(nullable: false),
                        p6Item5 = c.Int(nullable: false),
                        p6Item6 = c.Int(nullable: false),
                        p7Item1 = c.Int(nullable: false),
                        p7Item2 = c.Int(nullable: false),
                        p7Item3 = c.Int(nullable: false),
                        p7Item4 = c.Int(nullable: false),
                        p7Item5 = c.Int(nullable: false),
                        p7Item6 = c.Int(nullable: false),
                        p8Item1 = c.Int(nullable: false),
                        p8Item2 = c.Int(nullable: false),
                        p8Item3 = c.Int(nullable: false),
                        p8Item4 = c.Int(nullable: false),
                        p8Item5 = c.Int(nullable: false),
                        p8Item6 = c.Int(nullable: false),
                        p9Item1 = c.Int(nullable: false),
                        p9Item2 = c.Int(nullable: false),
                        p9Item3 = c.Int(nullable: false),
                        p9Item4 = c.Int(nullable: false),
                        p9Item5 = c.Int(nullable: false),
                        p9Item6 = c.Int(nullable: false),
                        p10Item1 = c.Int(nullable: false),
                        p10Item2 = c.Int(nullable: false),
                        p10Item3 = c.Int(nullable: false),
                        p10Item4 = c.Int(nullable: false),
                        p10Item5 = c.Int(nullable: false),
                        p10Item6 = c.Int(nullable: false),
                        p1Kills = c.Int(nullable: false),
                        p1Deaths = c.Int(nullable: false),
                        p1Assists = c.Int(nullable: false),
                        p2Kills = c.Int(nullable: false),
                        p2Deaths = c.Int(nullable: false),
                        p2Assists = c.Int(nullable: false),
                        p3Kills = c.Int(nullable: false),
                        p3Deaths = c.Int(nullable: false),
                        p3Assists = c.Int(nullable: false),
                        p4Kills = c.Int(nullable: false),
                        p4Deaths = c.Int(nullable: false),
                        p4Assists = c.Int(nullable: false),
                        p5Kills = c.Int(nullable: false),
                        p5Deaths = c.Int(nullable: false),
                        p5Assists = c.Int(nullable: false),
                        p6Kills = c.Int(nullable: false),
                        p6Deaths = c.Int(nullable: false),
                        p6Assists = c.Int(nullable: false),
                        p7Kills = c.Int(nullable: false),
                        p7Deaths = c.Int(nullable: false),
                        p7Assists = c.Int(nullable: false),
                        p8Kills = c.Int(nullable: false),
                        p8Deaths = c.Int(nullable: false),
                        p8Assists = c.Int(nullable: false),
                        p9Kills = c.Int(nullable: false),
                        p9Deaths = c.Int(nullable: false),
                        p9Assists = c.Int(nullable: false),
                        p10Kills = c.Int(nullable: false),
                        p10Deaths = c.Int(nullable: false),
                        p10Assists = c.Int(nullable: false),
                        p1Level = c.Int(nullable: false),
                        p2Level = c.Int(nullable: false),
                        p3Level = c.Int(nullable: false),
                        p4Level = c.Int(nullable: false),
                        p5Level = c.Int(nullable: false),
                        p6Level = c.Int(nullable: false),
                        p7Level = c.Int(nullable: false),
                        p8Level = c.Int(nullable: false),
                        p9Level = c.Int(nullable: false),
                        p10Level = c.Int(nullable: false),
                        p1CS = c.Int(nullable: false),
                        p2CS = c.Int(nullable: false),
                        p3CS = c.Int(nullable: false),
                        p4CS = c.Int(nullable: false),
                        p5CS = c.Int(nullable: false),
                        p6CS = c.Int(nullable: false),
                        p7CS = c.Int(nullable: false),
                        p8CS = c.Int(nullable: false),
                        p9CS = c.Int(nullable: false),
                        p10CS = c.Int(nullable: false),
                        p1Damage = c.Int(nullable: false),
                        p2Damage = c.Int(nullable: false),
                        p3Damage = c.Int(nullable: false),
                        p4Damage = c.Int(nullable: false),
                        p5Damage = c.Int(nullable: false),
                        p6Damage = c.Int(nullable: false),
                        p7Damage = c.Int(nullable: false),
                        p8Damage = c.Int(nullable: false),
                        p9Damage = c.Int(nullable: false),
                        p10Damage = c.Int(nullable: false),
                        p1Gold = c.Int(nullable: false),
                        p2Gold = c.Int(nullable: false),
                        p3Gold = c.Int(nullable: false),
                        p4Gold = c.Int(nullable: false),
                        p5Gold = c.Int(nullable: false),
                        p6Gold = c.Int(nullable: false),
                        p7Gold = c.Int(nullable: false),
                        p8Gold = c.Int(nullable: false),
                        p9Gold = c.Int(nullable: false),
                        p10Gold = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.matchIndex);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.MatchDetailsModels");
        }
    }
}
